#!/bin/bash

# Incremental Builder Monitor
# Usage: ./monitor_builder.sh [session_name] [output_directory]
# Examples:
#   ./monitor_builder.sh                                    # Monitor default session, auto-detect output
#   ./monitor_builder.sh my_session                         # Monitor custom session, auto-detect output  
#   ./monitor_builder.sh my_session train_pc_1000          # Monitor custom session and specific output dir
#   ./monitor_builder.sh "" train_nc_1000                  # Monitor default session and specific output dir

# Parse arguments
DEFAULT_SESSION_NAME="incremental_builder"
SESSION_NAME=${1:-$DEFAULT_SESSION_NAME}
OUTPUT_DIR=${2:-""}

# Handle empty string for session name (when user wants default session but specify output dir)
if [ "$SESSION_NAME" = "" ]; then
    SESSION_NAME=$DEFAULT_SESSION_NAME
fi

echo "🔍 Monitoring Incremental Builder"
echo "================================="
echo "Session: $SESSION_NAME"
if [ -n "$OUTPUT_DIR" ]; then
    echo "Output Directory: $OUTPUT_DIR"
fi
echo "Time: $(date)"
echo ""

# Auto-capture and document the actual command being run
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "📋 Auto-documenting running command..."
    
    # Extract the actual command from the running process
    ACTUAL_COMMAND=$(ps -ef | grep incremental_builder | grep -v grep | head -1 | sed 's/.*python -m/python -m/')
    
    if [ -n "$ACTUAL_COMMAND" ]; then
        # Create documentation file in the output directory if it exists
        if [ -n "$OUTPUT_DIR" ] && [ -d "$OUTPUT_DIR" ]; then
            DOC_FILE="$OUTPUT_DIR/INCREMENTAL_BUILDER_RUN_LOG.md"
            
            # Create or update the documentation
            cat > "$DOC_FILE" << EOF
# Incremental Builder Run Documentation

**Auto-generated by monitor_builder.sh at $(date)**

## Command Executed

\`\`\`bash
$ACTUAL_COMMAND
\`\`\`

## Run Details

- **Session Name:** $SESSION_NAME
- **Output Directory:** $OUTPUT_DIR
- **Start Time:** $(ps -o lstart= -p $(pgrep -f incremental_builder) 2>/dev/null | head -1 | xargs)
- **Process ID:** $(pgrep -f incremental_builder 2>/dev/null | head -1)
- **Monitoring Time:** $(date)

## Expected Outputs

Based on the command parameters:

### Directory Structure
\`\`\`
$OUTPUT_DIR/
├── master/                    # Final training dataset
│   ├── batch_00001.parquet
│   ├── batch_00002.parquet
│   └── ...
└── INCREMENTAL_BUILDER_RUN_LOG.md  # This documentation
\`\`\`

### Command Analysis
EOF

            # Parse command parameters and add analysis
            if echo "$ACTUAL_COMMAND" | grep -q "\--n-genes"; then
                N_GENES=$(echo "$ACTUAL_COMMAND" | sed -n 's/.*--n-genes \([0-9]*\).*/\1/p')
                echo "- **Gene Count:** $N_GENES baseline genes" >> "$DOC_FILE"
            fi
            
            if echo "$ACTUAL_COMMAND" | grep -q "\--gene-ids-file"; then
                GENE_FILE=$(echo "$ACTUAL_COMMAND" | sed -n 's/.*--gene-ids-file \([^ ]*\).*/\1/p')
                if [ -f "$GENE_FILE" ]; then
                    ADDITIONAL_COUNT=$(tail -n +2 "$GENE_FILE" 2>/dev/null | wc -l)
                    echo "- **Additional Genes:** $ADDITIONAL_COUNT from $GENE_FILE" >> "$DOC_FILE"
                    echo "- **Total Expected Genes:** ~$((N_GENES + ADDITIONAL_COUNT)) (depending on overlap)" >> "$DOC_FILE"
                fi
            fi
            
            if echo "$ACTUAL_COMMAND" | grep -q "\--batch-size"; then
                BATCH_SIZE=$(echo "$ACTUAL_COMMAND" | sed -n 's/.*--batch-size \([0-9]*\).*/\1/p')
                echo "- **Batch Size:** $BATCH_SIZE genes per batch" >> "$DOC_FILE"
            fi
            
            if echo "$ACTUAL_COMMAND" | grep -q "\--kmer-sizes"; then
                KMER_SIZES=$(echo "$ACTUAL_COMMAND" | sed -n 's/.*--kmer-sizes \([0-9 ]*\).*/\1/p')
                echo "- **K-mer Sizes:** $KMER_SIZES" >> "$DOC_FILE"
            fi
            
            # Add monitoring section
            cat >> "$DOC_FILE" << EOF

## Real-time Status

Last updated: $(date)

\`\`\`bash
# Monitor this run:
./meta_spliceai/splice_engine/meta_models/builder/docs/tmux/monitor_builder.sh $SESSION_NAME $OUTPUT_DIR

# Attach to session:
tmux a -t $SESSION_NAME

# Check output files:
ls -la $OUTPUT_DIR/master/

# View recent progress:
tmux capture-pane -t $SESSION_NAME -p | tail -10
\`\`\`

---
*This file is automatically updated by the monitoring script*
EOF
            
            echo "  📄 Documentation created: $DOC_FILE"
        else
            echo "  ⚠️  Output directory not specified or doesn't exist yet"
        fi
        
        echo "  🔧 Command: $(echo "$ACTUAL_COMMAND" | cut -c1-80)..."
    else
        echo "  ⚠️  Could not extract command details"
    fi
    echo ""
fi

# Check if session exists
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "✅ Session '$SESSION_NAME' is running"
    
    # Get session info
    SESSION_INFO=$(tmux ls -F "#{session_name}: #{session_windows} windows (created #{session_created_string}) [#{session_width}x#{session_height}]" | grep "^$SESSION_NAME:")
    echo "📊 $SESSION_INFO"
    echo ""
    
    # Show recent output
    echo "📝 Recent output (last 10 lines):"
    echo "-----------------------------------"
    tmux capture-pane -t "$SESSION_NAME" -p | tail -10
    echo ""
    
    # Check for output directories
    echo "📁 Checking for output directories..."
    
    FOUND_OUTPUT=false
    
    if [ -n "$OUTPUT_DIR" ]; then
        # User specified an output directory
        if [ -d "$OUTPUT_DIR" ]; then
            if [ -d "$OUTPUT_DIR/master" ]; then
                FOUND_OUTPUT=true
                echo "📁 Output directory: $OUTPUT_DIR (user-specified)"
                
                # Count files in master directory
                FILE_COUNT=$(ls "$OUTPUT_DIR/master" 2>/dev/null | wc -l)
                echo "  • Files created: $FILE_COUNT"
                
                # Show disk usage
                DISK_USAGE=$(du -sh "$OUTPUT_DIR" 2>/dev/null | cut -f1)
                echo "  • Disk usage: $DISK_USAGE"
                
                # Show latest files
                echo "  • Latest files:"
                ls -lt "$OUTPUT_DIR/master" 2>/dev/null | head -3 | while read line; do
                    echo "    $line"
                done
                echo ""
                
                # Update auto-generated documentation with current progress
                DOC_FILE="$OUTPUT_DIR/INCREMENTAL_BUILDER_RUN_LOG.md"
                if [ -f "$DOC_FILE" ]; then
                    # Extract current progress from tmux output
                    CURRENT_PROGRESS=$(tmux capture-pane -t "$SESSION_NAME" -p | grep "Processing gene sequences" | tail -1 | sed 's/.*Processing gene sequences: *\([^|]*\).*/\1/' | tr -d ' ')
                    
                    # Update the status section in the documentation
                    sed -i '/## Real-time Status/,$d' "$DOC_FILE"
                    cat >> "$DOC_FILE" << EOF

## Real-time Status

Last updated: $(date)

### Current Progress
- **Files created:** $FILE_COUNT
- **Disk usage:** $DISK_USAGE  
- **Processing status:** ${CURRENT_PROGRESS:-"In progress..."}

### Recent Activity
\`\`\`
$(tmux capture-pane -t "$SESSION_NAME" -p | tail -5)
\`\`\`

### Quick Commands
\`\`\`bash
# Monitor this run:
./meta_spliceai/splice_engine/meta_models/builder/docs/tmux/monitor_builder.sh $SESSION_NAME $OUTPUT_DIR

# Attach to session:
tmux a -t $SESSION_NAME

# Check output files:
ls -la $OUTPUT_DIR/master/

# View recent progress:
tmux capture-pane -t $SESSION_NAME -p | tail -10
\`\`\`

---
*This file is automatically updated by the monitoring script*
EOF
                fi
            else
                echo "📁 Output directory: $OUTPUT_DIR (user-specified)"
                echo "  • ⚠️  Master directory not found yet ($OUTPUT_DIR/master)"
                echo ""
            fi
        else
            echo "📁 Output directory: $OUTPUT_DIR (user-specified)"
            echo "  • ⚠️  Directory not found yet"
            echo ""
        fi
    else
        # Auto-detect output directories
        echo "  • Auto-detecting output directories..."
        
        # First check common known directories
        COMMON_OUTPUT_DIRS=("train_pc_1000_plus_custom_3mers" "train_pc_1000_3mers" "train_pc_5000_3mers" "train_pc_20000_3mers")
        
        # Also auto-detect any directory containing a 'master' subdirectory
        AUTO_DETECTED_DIRS=()
        while IFS= read -r -d '' dir; do
            dirname=$(basename "$dir")
            # Skip hidden directories and common non-output directories
            if [[ ! "$dirname" =~ ^[.] ]] && [[ "$dirname" != "master" ]] && [[ "$dirname" =~ (train_|test_|data_|pc_|nc_|custom_|genes_) ]]; then
                AUTO_DETECTED_DIRS+=("$dirname")
            fi
        done < <(find . -maxdepth 2 -name "master" -type d -printf '%h\0' 2>/dev/null)
        
        # Combine and deduplicate directories
        ALL_DIRS=($(printf '%s\n' "${COMMON_OUTPUT_DIRS[@]}" "${AUTO_DETECTED_DIRS[@]}" | sort -u))
        
        for dir in "${ALL_DIRS[@]}"; do
            if [ -d "$dir" ] && [ -d "$dir/master" ]; then
                FOUND_OUTPUT=true
                echo "📁 Output directory: $dir (auto-detected)"
                
                # Count files in master directory
                FILE_COUNT=$(ls "$dir/master" 2>/dev/null | wc -l)
                echo "  • Files created: $FILE_COUNT"
                
                # Show disk usage
                DISK_USAGE=$(du -sh "$dir" 2>/dev/null | cut -f1)
                echo "  • Disk usage: $DISK_USAGE"
                
                # Show latest files
                echo "  • Latest files:"
                ls -lt "$dir/master" 2>/dev/null | head -3 | while read line; do
                    echo "    $line"
                done
                echo ""
                
                # Update auto-generated documentation with current progress
                DOC_FILE="$dir/INCREMENTAL_BUILDER_RUN_LOG.md"
                if [ -f "$DOC_FILE" ]; then
                    # Extract current progress from tmux output
                    CURRENT_PROGRESS=$(tmux capture-pane -t "$SESSION_NAME" -p | grep "Processing gene sequences" | tail -1 | sed 's/.*Processing gene sequences: *\([^|]*\).*/\1/' | tr -d ' ')
                    
                    # Update the status section in the documentation
                    sed -i '/## Real-time Status/,$d' "$DOC_FILE"
                    cat >> "$DOC_FILE" << EOF

## Real-time Status

Last updated: $(date)

### Current Progress
- **Files created:** $FILE_COUNT
- **Disk usage:** $DISK_USAGE  
- **Processing status:** ${CURRENT_PROGRESS:-"In progress..."}

### Recent Activity
\`\`\`
$(tmux capture-pane -t "$SESSION_NAME" -p | tail -5)
\`\`\`

### Quick Commands
\`\`\`bash
# Monitor this run:
./meta_spliceai/splice_engine/meta_models/builder/docs/tmux/monitor_builder.sh $SESSION_NAME $dir

# Attach to session:
tmux a -t $SESSION_NAME

# Check output files:
ls -la $dir/master/

# View recent progress:
tmux capture-pane -t $SESSION_NAME -p | tail -10
\`\`\`

---
*This file is automatically updated by the monitoring script*
EOF
                fi
            fi
        done
        
        if [ "$FOUND_OUTPUT" = false ]; then
            echo "  • No output directories found yet"
            echo "  • Tip: Specify output directory: ./monitor_builder.sh $SESSION_NAME your_output_dir"
            echo ""
        fi
    fi
    
    # Check for log files
    LOG_FILES=(*.log builder_*.log incremental_builder*.log)
    FOUND_LOGS=false
    
    for pattern in "${LOG_FILES[@]}"; do
        if ls $pattern 1> /dev/null 2>&1; then
            FOUND_LOGS=true
            echo "📄 Log files found:"
            ls -lt $pattern | head -3 | while read line; do
                echo "  $line"
            done
            break
        fi
    done
    
    if [ "$FOUND_LOGS" = false ]; then
        echo "📄 No log files found in current directory"
    fi
    echo ""
    
    # Show system resources
    echo "💻 System resources:"
    echo "  • Memory: $(free -h | grep '^Mem:' | awk '{print $3 "/" $2 " (" $3/$2*100 "% used)"}')"
    echo "  • Disk: $(df -h . | tail -1 | awk '{print $3 "/" $2 " (" $5 " used)"}')"
    
    # Check if process is actually running
    if pgrep -f "incremental_builder" > /dev/null; then
        echo "  • Process: ✅ Running"
        
        # Show CPU usage
        CPU_USAGE=$(top -bn1 | grep "python.*incremental_builder" | head -1 | awk '{print $9}')
        if [ -n "$CPU_USAGE" ]; then
            echo "  • CPU usage: ${CPU_USAGE}%"
        fi
    else
        echo "  • Process: ⚠️  Not found (may have completed or failed)"
    fi
    echo ""
    
    # Show useful commands
    echo "📋 Useful commands:"
    echo "  • Attach to session:    tmux a -t $SESSION_NAME"
    echo "  • View full log:        tail -f *.log"
    if [ -n "$OUTPUT_DIR" ]; then
        echo "  • Check output:         ls -la $OUTPUT_DIR/master/"
    else
        echo "  • Check output:         ls -la */master/"
    fi
    echo "  • Kill session:         tmux kill-session -t $SESSION_NAME"
    echo "  • Monitor specific dir: ./monitor_builder.sh $SESSION_NAME your_output_dir"
    
else
    echo "❌ Session '$SESSION_NAME' is not running"
    echo ""
    
    # Show available sessions
    if tmux ls >/dev/null 2>&1; then
        echo "📋 Available sessions:"
        tmux ls
    else
        echo "📋 No tmux sessions found"
    fi
    echo ""
    
    # Check if process is running outside tmux
    if pgrep -f "incremental_builder" > /dev/null; then
        echo "⚠️  Incremental builder process found running outside tmux:"
        ps aux | grep "incremental_builder" | grep -v grep
    else
        echo "ℹ️  No incremental builder processes found"
    fi
    echo ""
    
    # Show how to start
    echo "🚀 To start a new session:"
    echo "  ./run_builder.sh"
    echo "  or"
    echo "  tmux new-session -d -s $SESSION_NAME 'conda activate surveyor && python -m meta_spliceai.splice_engine.meta_models.builder.incremental_builder [options]'"
    echo ""
    echo "💡 Monitor tips:"
    echo "  • Monitor with auto-detection:     ./monitor_builder.sh"
    echo "  • Monitor specific output dir:     ./monitor_builder.sh \"\" train_nc_1000"
    echo "  • Monitor custom session:          ./monitor_builder.sh my_session train_pc_5000"
fi

echo ""
echo "🔄 Run this script again to refresh status" 