import numpy as np
from scipy import stats

num_samples = 17

# Suppose we use the good old t-test to compare two groups of samples ...
# > Generate sample data with hypothetical PSI values
sample_names = [f"SRR{i}" for i in range(1, num_samples+1)]

def generate_data(num_samples):
    low_group = np.random.uniform(0.2, 0.4, num_samples)
    high_group = np.random.uniform(0.8, 0.95, num_samples)
    return low_group, high_group

low_group, high_group = generate_data(num_samples)

############################################

# Combine data (for the pooling & shuffling step)
combined_data = np.concatenate([low_group, high_group])

# Calculate original t-test
t_stat, p_value = stats.ttest_ind(low_group, high_group)
observed_t_stat = t_stat

# Permutation test
num_permutations = 1000
permuted_t_stats = []

# Create null distribution for t-statistics
# > The null distribution of t-statistics is generated by shuffling the labels and recalculating the t-statistic many times.
for _ in range(num_permutations):
    np.random.shuffle(combined_data)
    new_low_group = combined_data[:17]
    new_high_group = combined_data[17:]
    t_stat, _ = stats.ttest_ind(new_low_group, new_high_group)
    permuted_t_stats.append(t_stat)

# Calculate p-value
# > Compare the observed t-statistic to the null distribution to determine how extreme it is relative to 
#   what would be expected by chance.
permuted_t_stats = np.array(permuted_t_stats)
p_value_permutation = np.sum(np.abs(permuted_t_stats) >= np.abs(observed_t_stat)) / num_permutations

print(f"Observed t-statistic: {observed_t_stat}")
print(f"P-value (permutation test): {p_value_permutation}")
